export default {
  index: 'Overview',
  lakerunner: 'Lakerunner',
  postgres: 'PostgreSQL',
  bigquery: 'Google BigQuery',
  snowflake: 'Snowflake',
  athena: 'Amazon Athena',
  clickhouse: 'ClickHouse',
  github: 'GitHub',
  jira: 'Jira',
  servicenow: 'ServiceNow',
  confluence: 'Confluence',
  slack: 'Slack',
  teams: 'Microsoft Teams',
  pagerduty: 'PagerDuty',
}
